### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by amadden80** [tquillin/bistro#1]
Please edit your readme!   This is the most important document in the project.

I see a lot of commented out code in your project.
Since we are using git, we can always bring that code back later.
I want you to jump through you project and clean things up.

I am not seeing several of the features we need to see for this project.  Is the version on heroku the complete version?  Please let me know here asap.

**Comment by tquillin** [comment]
The version on Heroku is the same as the github version.

Terrell Quillin,
Full Stack Web Developer
832-540-8340
